remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
author: Matthias Himmelmann
title: Matthias Himmelmann
description: PhD Student, Universit√§t Potsdam
logo: images/Bewerbungsfoto20183.JPG
